version: "3.8"
services:
  redis-like:
    build:
      context: ./redis-like
      dockerfile: Dockerfile.redis
    expose: ["4000"]
    networks: [internal]

  api:
    build:
      context: ./kv-service
      dockerfile: Dockerfile.kv.dev
    ports: ["8080:3000"]
    environment:
      REDIS_URL: http://redis-like:4000
    volumes:
      - ./kv-service:/app
      - /app/node_modules
    depends_on: [redis-like]
    networks: [internal]

networks:
  internal:
