services:
  redis:
    build:
      context: ./redis-like
      dockerfile: Dockerfile.redis
    expose: ["4000"]
    networks:
      internal:
        aliases:
          - redis

  kv:
    build:
      context: ./kv-service
      dockerfile: Dockerfile.kv
    ports: ["8080:3000"]
    environment:
      REDIS_URL: http://redis:4000
    depends_on: [redis]
    networks:
      internal:
        aliases:
          - kv

networks:
  internal:
    driver: bridge
