name: 'Build and Push Docker Image'
description: 'Build Node.js app and push Docker image to GHCR'
inputs:
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context-path:
    description: 'Build context path'
    required: false
    default: '.'
  registry-username:
    description: 'Registry username'
    required: true
  registry-password:
    description: 'Registry password'
    required: true
outputs:
  image-tag:
    description: 'Built Docker image tag'
    value: ${{ steps.build.outputs.image-tag }}
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build application
      run: npm run build
      shell: bash

    - name: Build Docker image
      id: build
      run: |
        IMAGE_TAG="ghcr.io/${{ github.repository }}:${{ github.sha }}"
        docker build -f ${{ inputs.dockerfile-path }} -t $IMAGE_TAG ${{ inputs.context-path }}
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      shell: bash

    - name: Log in to GitHub Container Registry
      run: echo "${{ inputs.registry-password }}" | docker login ghcr.io -u "${{ inputs.registry-username }}" --password-stdin
      shell: bash

    - name: Push Docker image
      run: |
        IMAGE_TAG="ghcr.io/${{ github.repository }}:${{ github.sha }}"
        docker push $IMAGE_TAG
      shell: bash
