version: "3.8"

services:
  tea-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tea-tracker-api
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY:-tea-secret-key}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/tea",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tea-network

networks:
  tea-network:
    driver: bridge
